---
- name: Template child stream.conf
  ansible.builtin.template:
    src: stream-child.conf.j2
    dest: /etc/netdata/stream.conf
    owner: netdata
    group: netdata
    mode: '0640'
  notify: restart netdata

- name: Template child netdata.conf
  ansible.builtin.template:
    src: netdata-child.conf.j2
    dest: /etc/netdata/netdata.conf
    owner: netdata
    group: netdata
    mode: '0644'
  notify: restart netdata
