all:
  children:
    netdata_parents:
      hosts:
        docker-host:
          ansible_host: docker-host
          ansible_user: teej
          ansible_become: true
    netdata_children:
      hosts:
        proxmox:
          ansible_host: proxmox
          ansible_user: teej
          ansible_become: true
        pihole:
          ansible_host: pihole
          ansible_user: teej
          ansible_become: true
          netdata_stream_api_key: "c7071b1d-fc66-43a2-8f79-784b44963c8e"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    netdata_parent_host: "192.168.1.157"
    netdata_parent_port: 19999
