all:
  children:
    netdata_parents:
      hosts:
        docker-host:
          ansible_host: docker-host
          ansible_user: teej
          ansible_become: true
    netdata_children:
      hosts:
        proxmox:
          ansible_host: proxmox
          ansible_user: teej
          ansible_become: true
        pihole:
          ansible_host: pihole
          ansible_user: teej
          ansible_become: true
          netdata_stream_api_key: "<4223cfc7-c08b-4645-d62f38e35a0a>"
  vars:
    ansible_python_interpreter: /usr/bin/python3
    netdata_parent_host: "192.168.1.157"
    netdata_parent_port: 19999
